server:
    port: 8080
spring:
    datasource:
        name: localhost  #????
        url: jdbc:mariadb://localhost:3306/mysql?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false #url
        username: root  #???
        password: 85426  #??
        driver-class-name: org.mariadb.jdbc.Driver  #???????

